export const TEST_BY_PERSONNEL = [
  "Mohamed Kamel",
  "Wael Hassan",
  "Ahmed Fattouh",
  "Mohamed Salama",
  "Ayman Saied",
  "Alaa El-Sayed",
  "Mohamed Ghoniem"
];

// Official Deduplicated Supplier Database List - Ready for Combobox Consumption
export const SUPPLIER_LIST = [
  "ACCM",
  "ACISELSAN",
  "AFM",
  "AL Watani Chemicals",
  "Al-Ahram for Transport and Supplies",
  "Al-Eman Co",
  "Alex mining Company (AMCO)",
  "Alex Wetec Co.",
  "AL-KARMA Industry and mining co.",
  "Al-Kout industrial projects",
  "Al-Thurya",
  "Amoun",
  "Arab Potash",
  "ASCOM",
  "AZF Hydraulic Services",
  "Bahgat",
  "Calkam UK Limited",
  "Chem TEC FZ",
  "Corundum",
  "Dara Oil Services",
  "Delta EgyChem",
  "DENKIM",
  "DFI-Target",
  "Drilling Fluids Technologies (DFT)",
  "Drilling Specialties Company",
  "Egypt Nanotechnologies Co. S.A.E.",
  "Egyptian Canadian Co For Chemical Industries (E.C.C.)",
  "Egyptian Co. For Supplying Chemicals and Derivatives (Chemacid)",
  "EGY-Services Group",
  "El-Kayar Imp.-Exp",
  "El-Mohandes",
  "EL-Watanya",
  "El-Yousr",
  "EMDAD for commercial agencies and factory services",
  "EMEC R&D Lab.",
  "ENERGY",
  "Energyya Petrochem",
  "EVERGROW",
  "GL Chemicals",
  "Global Chemical Company",
  "GLOBE CHEM",
  "GPC",
  "Green Matter",
  "Gumpro Drilling Fluids",
  "HAMCO for Building Materials",
  "Horizon Chemicals",
  "ICID",
  "Impact Solution Group",
  "Innospec Oilfield Services",
  "International Clay and minerals Company (ICMC)",
  "International Company For Mining & Investments (ICMI)",
  "Kemira",
  "Kuwait Technical Company (K.T.C)",
  "Lamberti",
  "Life Chemicals Group (L.C.G)",
  "Linyi",
  "Lotte Fine Chemical",
  "M.I.A. for Chemicals Supply",
  "MAGNESIUM EGYPT",
  "Mediterranean Drilling Fluids (MDF)",
  "Morgan Speciality Chemicals",
  "Mukund Industries",
  "Multi Service Company",
  "NETCO OIL SERVICES (NETCO)",
  "OLEON",
  "Optimize Specialty Chemicals",
  "Oren Hydrocarbons Middle East FZ (OREN)",
  "PCS Specialty Chemicals Via EMEC R&D Lab.",
  "PETASCO (Petroleum Equipment Trading and services Co.)",
  "Petro Zone Oil Field Supplies",
  "Planet Chemical Free Zone (PCFZ)",
  "Pyramids Petroleum Services",
  "Qingdao Doeast Chemical CO., LTD.",
  "Qingdao Green Chemicals",
  "R & D Lab.",
  "REDA Energy Via EMEC R&D Lab.",
  "RP Minerals Free Zone",
  "SDF",
  "Shandong Head group",
  "Shandong Square Sea Rubber Technology Co.",
  "Shijiazhuang Taixu Biology Technology Co.",
  "SHREE GR",
  "Sigma Supplies Co.",
  "Sirte Oil Co.",
  "Skytech Chemical Limited",
  "Speciality Chemicals",
  "Specialized Energy Ventures",
  "Specialized Energy Ventures for Chemicals Co.(7CHEM Energy & chemicals)",
  "Sphinx Milling Station",
  "SUN Specialty Products (SUN)",
  "Target for Chemicals Industry and Trade (Target)",
  "TCB -Brinadd",
  "Tiba",
  "TORA",
  "United Mud Chem Pvt. Ltd. (UMC)",
  "USCO",
  "World White Group",
  "World White Trade Co.",
  "Zhejiang Fenghong New Material Co. Ltd.",
  "Zinc Egypt"
];
